### PR TITLE
proposed clean-up, stage 1

### PR DESCRIPTION
**Pull request by colinclassic**
small changes to README. refactored apiupload & presencecheck into single file: slack_api. updated front_door to reflect.

### CODE REVIEW

**Comment by colinclassic** [comment]
Review the files changed and tell me what you think.
Also, we should test that this actually still works on the Pi before doing the merge.

**Comment by CandyManCan** [comment]
I like it. Centralizes the api code

**Comment by leenyman** [comment]
while we're at it why don't we pull the channel out of the slack_api file and move it to the data.json

**Comment by leenyman** [comment]
I can also do that separately as these changes look good to me.

**Pull request merged**
